(()=>{'use strict';
const $=id=>document.getElementById(id);
const norm=s=>String(s??'').replace(/^\uFEFF/,'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const num=s=>{let v=String(s??'').trim();if(!v)return 0;v=v.replace(/\s/g,'');if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(v))v=v.replace(/\./g,'').replace(',','.');else if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(v))v=v.replace(/,/g,'');else v=v.replace(/[^0-9,.-]/g,'').replace(/,(?=\d{1,2}$)/,'.').replace(/,/g,'');const n=Number(v);return Number.isFinite(n)?n:0};
function parseCSV(text){text=String(text||'').replace(/^\uFEFF/,'');const first=text.split(/\r?\n/,1)[0]||'';let semi=0,comma=0,tab=0,q=false;for(let i=0;i<first.length;i++){const c=first[i];if(c==='"')q=!q;else if(!q){if(c===';')semi++;else if(c===',')comma++;else if(c==='\t')tab++}}const d=semi>=comma&&semi>=tab?';':tab>comma?'\t':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===d&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];cell=''}else cell+=c}if(cell!==''||row.length){row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row)}return {rows,delimiter:d}}
function findHeader(rows){const wanted=['kodeitem','kode','code','sku','kodebarang','kodebarcode','barcode','namaitem','namabarang','nama','name','productname'];let best=-1,score=0;const limit=Math.min(rows.length,40);for(let r=0;r<limit;r++){const h=rows[r].map(norm);let s=0;for(const w of wanted)if(h.includes(w))s++;if(h.includes('kodeitem'))s+=3;if(h.includes('namaitem'))s+=3;if(s>score){score=s;best=r}}return score>=2?best:-1}
function idxMap(h){const aliases={code:['kodeitem','kode','code','sku','kodebarang','itemcode'],barcode:['kodebarcode','barcode','ean','upc'],name:['namaitem','namabarang','nama','name','productname','itemname'],jenis:['jenis','type','kategori','category'],brand:['merek','brand','manufacturer'],stok:['stok','stock','qty','quantity'],satuan:['satuan','unit','uom'],cost:['hargabeli','hargapokok','purchaseprice','cost','buyprice'],price:['hargajual','harga','price','sellingprice'],stokmin:['stokmin','minimumstock','minstock'],rak:['rak','lokasi','location'],supplier:['supplier','pemasok'],keterangan:['keterangan','catatan','note','notes']};const out={};for(const k in aliases){out[k]=-1;for(const a of aliases[k]){const i=h.indexOf(a);if(i>=0){out[k]=i;break}}}return out}
function val(row,i){return i>=0?String(row[i]??'').trim():''}
function status(t,ok){const e=$('nfCrudStatus');if(e){e.textContent=t;e.style.color=ok?'#087f63':'#c85050'}}
function run(file){const rd=new FileReader();rd.onload=()=>{try{if(!(window.Android&&typeof Android.importProducts==='function'))throw Error('Database native belum tersedia.');const parsed=parseCSV(rd.result);const rows=parsed.rows;if(!rows.length)throw Error('CSV kosong.');const hi=findHeader(rows);if(hi<0)throw Error('Header CSV tidak ditemukan. Pastikan ada kolom Kode Item atau Nama Item.');const h=rows[hi].map(norm),m=idxMap(h);if(m.code<0&&m.barcode<0&&m.name<0)throw Error('Kolom Kode Item/Nama Item/Barcode tidak ditemukan.');const data=[];for(let r=hi+1;r<rows.length;r++){const row=rows[r];const x={code:val(row,m.code),barcode:val(row,m.barcode),name:val(row,m.name),jenis:val(row,m.jenis),brand:val(row,m.brand),satuan:val(row,m.satuan),cost:num(val(row,m.cost)),price:num(val(row,m.price)),stok:num(val(row,m.stok)),rak:val(row,m.rak)};if(x.name||x.code||x.barcode)data.push(x)}if(!data.length)throw Error('Tidak ada item valid setelah header CSV.');const mode=$('nfCrudMode')?.value||'add_update';const res=JSON.parse(Android.importProducts(JSON.stringify(data),mode));if(!res.ok)throw Error(res.error||'Import gagal');status('✓ Import berhasil: '+(res.added||0)+' ditambah, '+(res.updated||0)+' diperbarui. Total diproses '+data.length+'. Delimiter: '+JSON.stringify(parsed.delimiter),true);if(typeof window.render==='function')window.render();else if($('nfCrudSearch'))$('nfCrudSearch').dispatchEvent(new Event('input'));}catch(e){status('Import gagal: '+(e.message||e),false)}finally{const f=$('nfCrudFile');if(f)f.value=''}};rd.onerror=()=>status('Import gagal: file tidak dapat dibaca.',false);rd.readAsText(file,'UTF-8')}
function boot(){const b=$('nfCrudImport'),f=$('nfCrudFile');if(!b||!f)return; b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();f.click()}; f.onchange=e=>{e.stopImmediatePropagation();const file=f.files?.[0];if(file)run(file)};b.dataset.csvV2='1'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300));else setTimeout(boot,300);
new MutationObserver(()=>boot()).observe(document.documentElement,{childList:true,subtree:true});
})();
