(()=>{'use strict';
const KEY='naufal_farma_items_v1';
const $=id=>document.getElementById(id);
const R=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=[['code','Kode Item'],['barcode','Barcode'],['name','Nama Item'],['jenis','Jenis'],['merek','Merek'],['satuan','Satuan'],['cost','Harga Beli'],['price','Harga Jual'],['stock','Stok'],['rak','Rak'],['supplier','Supplier'],['keterangan','Keterangan']];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x)&&x.length){ITEMS.splice(0,ITEMS.length,...x);return true}}catch(e){}return false}
function save(){localStorage.setItem(KEY,JSON.stringify(ITEMS))}
function seed(){if(!localStorage.getItem(KEY))save();else load()}
function styles(){if($('crudStyle'))return;let s=document.createElement('style');s.id='crudStyle';s.textContent=`#itemCrudSection{margin-top:14px;background:#fff;border:1px solid var(--line,#e3ebe8);border-radius:18px;padding:12px;box-shadow:var(--shadow,0 7px 24px rgba(20,70,58,.08))}.crud-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.crud-head h3{margin:0;font-size:15px}.crud-head small{color:var(--g,#0b8a69);font-weight:800}.crud-tools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.crud-tools button{min-height:42px;font-size:12px;font-weight:800}.crud-tools .add{grid-column:1/-1;background:var(--g,#0b8a69)}.crud-search{width:100%;height:44px!important;margin:0 0 8px;padding:0 12px!important;border-radius:12px!important;background:#f8fbfa!important}.crud-count{font-size:10px;color:var(--muted,#74827e);margin:5px 2px}.crud-list{display:flex;flex-direction:column;gap:7px;max-height:520px;overflow:auto}.crud-item{border:1px solid #e3ebe8;border-radius:13px;padding:10px;background:#fbfdfc}.crud-item-top{display:flex;justify-content:space-between;gap:8px}.crud-name{font-size:13px;font-weight:800;line-height:1.25}.crud-code{font-size:10px;color:#74827e;margin-top:3px}.crud-price{font-size:13px;font-weight:900;color:var(--g,#0b8a69);white-space:nowrap}.crud-meta{font-size:10px;color:#74827e;margin-top:6px}.crud-buttons{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.crud-buttons button{padding:7px;font-size:11px}.crud-edit{background:#eef7f4;color:var(--g,#0b8a69)}.crud-del{background:#fff0f0;color:#c44}.crud-modal{position:fixed;inset:0;background:#0008;z-index:3000;display:none;align-items:flex-end;justify-content:center;padding:10px}.crud-modal.show{display:flex}.crud-box{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;padding:15px}.crud-box h3{margin:0 0 12px}.crud-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.crud-field{display:flex;flex-direction:column;gap:4px}.crud-field.full{grid-column:1/-1}.crud-field label{font-size:10px;font-weight:800;color:#66736f}.crud-field input,.crud-field textarea{width:100%;padding:10px;border:1px solid #d9e4e0;border-radius:10px;font:inherit;font-size:14px;background:#f8fbfa}.crud-field textarea{min-height:70px;resize:vertical}.crud-modal-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.crud-modal-actions button{min-height:44px}.crud-modal-actions .ok{background:var(--g,#0b8a69)}.crud-modal-actions .cancel{background:#edf1ef;color:#34413d}@media(max-width:430px){.crud-grid{grid-template-columns:1fr}.crud-field.full{grid-column:auto}}`;document.head.appendChild(s)}
function menu(){let g=document.querySelector('.quick-grid');if(g&&!$('quickDaftarItem')){let b=document.createElement('button');b.id='quickDaftarItem';b.className='quick-btn q-indigo';b.innerHTML='<span>▤</span><b>Daftar Item</b><small>Kelola database</small>';b.onclick=focus;g.appendChild(b)}}
function section(){let x=document.createElement('section');x.id='itemCrudSection';x.className='card';x.innerHTML='<div class="crud-head"><h3>📦 Daftar Item</h3><small>CRUD DATABASE</small></div><input id="crudSearch" class="crud-search" placeholder="Cari nama, kode, atau barcode..." autocomplete="off"><div class="crud-tools"><button class="add" id="crudAdd">＋ Tambah Item</button><button id="crudImport">📥 Import CSV</button><button id="crudExport">📤 Export CSV</button></div><div id="crudCount" class="crud-count"></div><div id="crudList" class="crud-list"></div></section>';return x}
function modal(){let m=document.createElement('div');m.id='crudModal';m.className='crud-modal';m.innerHTML='<div class="crud-box"><h3 id="crudTitle">Tambah Item</h3><div class="crud-grid">'+fields.map(([k,l])=>'<div class="crud-field '+(['keterangan'].includes(k)?'full':'')+'"><label>'+l+'</label>'+ (k==='keterangan'?'<textarea id="f_'+k+'"></textarea>':'<input id="f_'+k+'" '+(['cost','price','stock'].includes(k)?'inputmode="numeric"':'')+'>')+'</div>').join('')+'</div><div class="crud-modal-actions"><button class="cancel" id="crudCancel">Batal</button><button class="ok" id="crudSave">Simpan</button></div></div>';document.body.appendChild(m);m.querySelector('#crudCancel').onclick=close;m.querySelector('#crudSave').onclick=commit}
let editIndex=-1;
function open(i=-1){editIndex=i;$("crudTitle").textContent=i<0?'Tambah Item':'Edit Item';fields.forEach(([k])=>{let e=$('f_'+k);e.value=i<0?'':(ITEMS[i]?.[k]??'')});$('crudModal').classList.add('show');setTimeout(()=>$('f_name').focus(),100)}
function close(){$('crudModal').classList.remove('show')}
function commit(){let x={};fields.forEach(([k])=>{let v=$('f_'+k).value.trim();x[k]=['cost','price','stock'].includes(k)?(Number(v.replace(/[^0-9-]/g,''))||0):v});if(!x.name){alert('Nama Item wajib diisi.');return}if(!x.code)x.code='AUTO-'+Date.now();if(editIndex<0)ITEMS.push(x);else ITEMS[editIndex]=x;save();close();render();refreshAll();alert('Data item tersimpan.');}
function del(i){if(!confirm('Hapus item '+(ITEMS[i]?.name||'')+'?'))return;ITEMS.splice(i,1);save();render();refreshAll()}
function render(){let q=String($('crudSearch')?.value||'').toLowerCase().trim(),a=ITEMS.map((x,i)=>({x,i})).filter(o=>{let x=o.x,s=[x.name,x.code,x.barcode,x.merek,x.jenis].join(' ').toLowerCase();return !q||s.includes(q)}).slice(0,100);$('crudCount').textContent='Menampilkan '+a.length+' dari '+ITEMS.length+' item';$('crudList').innerHTML=a.map(o=>{let x=o.x;return '<div class="crud-item"><div class="crud-item-top"><div><div class="crud-name">'+E(x.name)+'</div><div class="crud-code">'+E(x.code||'-')+(x.barcode?' • '+E(x.barcode):'')+'</div></div><div class="crud-price">'+R(x.price||0)+'</div></div><div class="crud-meta">Beli: '+R(x.cost||0)+' • '+E(x.satuan||'-')+' • Stok: '+E(x.stock??0)+' • Rak: '+E(x.rak||'-')+'</div><div class="crud-buttons"><button class="crud-edit" data-e="'+o.i+'">✏ Edit</button><button class="crud-del" data-d="'+o.i+'">🗑 Hapus</button></div></div>'}).join('')||'<div class="empty">Item tidak ditemukan.</div>';document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>open(+b.dataset.e));document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>del(+b.dataset.d))}
function refreshAll(){try{if(typeof renderItems==='function')renderItems();if(typeof search==='function')search();}catch(e){document.querySelectorAll('input').forEach(i=>{if(i.id==='searchInput')i.dispatchEvent(new Event('input'))})}}
function csvParse(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function importCsv(){let inp=document.createElement('input');inp.type='file';inp.accept='.csv,text/csv';inp.onchange=()=>{let f=inp.files?.[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let rows=csvParse(String(rd.result||''));if(rows.length<2)throw Error('CSV kosong');let h=rows[0].map(norm),map={code:['kodeitem','kode','kode_item'],barcode:['barcode','kodebarcode','kode_barcode'],name:['namaitem','nama','nama_item'],jenis:['jenis'],merek:['merek'],satuan:['satuan'],cost:['hargabeli','hargapokok','harga_beli','cost'],price:['hargajual','harga_jual','price'],stock:['stok','stock'],rak:['rak'],supplier:['supplier','supplier1'],keterangan:['keterangan']};let idx={};Object.keys(map).forEach(k=>idx[k]=map[k].map(norm).map(z=>h.indexOf(z)).find(i=>i>=0));let data=rows.slice(1).map(r=>{let x={};Object.keys(idx).forEach(k=>{let i=idx[k];let v=i>=0?r[i]:'';x[k]=['cost','price','stock'].includes(k)?(Number(String(v).replace(/[^0-9-]/g,''))||0):String(v||'').trim()});return x}).filter(x=>x.name);if(!data.length)throw Error('Kolom Nama Item tidak ditemukan');if(!confirm('Import '+data.length+' item? Data database aktif akan diganti dengan isi CSV.'))return;ITEMS.splice(0,ITEMS.length,...data);save();render();refreshAll();alert('Import selesai: '+data.length+' item.')}catch(e){alert('Import gagal: '+e.message)}};rd.readAsText(f,'UTF-8')};inp.click()}
function csvCell(v){let s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function exportCsv(){let head=['Kode Item','Barcode','Nama Item','Jenis','Merek','Satuan','Harga Beli','Harga Jual','Stok','Rak','Supplier','Keterangan'];let keys=['code','barcode','name','jenis','merek','satuan','cost','price','stock','rak','supplier','keterangan'];let csv='\ufeff'+head.join(',')+'\n'+ITEMS.map(x=>keys.map(k=>csvCell(x[k])).join(',')).join('\n');let fn='database_naufal_farma_'+new Date().toISOString().slice(0,10)+'.csv';if(window.Android&&typeof window.Android.saveReport==='function'){Android.saveReport(fn,csv,'text/csv');return}let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=fn;a.click()}
function focus(){let e=$('itemCrudSection');if(e)e.scrollIntoView({behavior:'smooth',block:'start'})}
function init(){seed();styles();menu();let r=$('laporanSection');if(!r||$('itemCrudSection'))return;r.parentNode.insertBefore(section(),r);modal();$('crudSearch').oninput=render;$('crudAdd').onclick=()=>open();$('crudImport').onclick=importCsv;$('crudExport').onclick=exportCsv;render();menu()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();