(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function native(){return !!(window.Android&&typeof Android.listProducts==='function'&&typeof Android.importProducts==='function'&&typeof Android.saveReport==='function')}
function parseCSV(t){t=String(t||'').replace(/^\uFEFF/,'');const lines=[];let row=[],cell='',q=false;let delim=',';const sample=t.split(/\r?\n/).slice(0,30).join('\n');const sc=(sample.match(/;/g)||[]).length,co=(sample.match(/,/g)||[]).length,ta=(sample.match(/\t/g)||[]).length;if(sc>=co&&sc>=ta)delim=';';else if(ta>co)delim='\t';for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===delim&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))lines.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))lines.push(row);return lines}
const norm=s=>String(s??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
function findHeader(rows){const wanted=['kodeitem','kode','code','kodebarang','barcode','kodebarcode','nama','namaitem','namabarang','name'];let best=-1,score=0;rows.slice(0,40).forEach((r,i)=>{const h=r.map(norm);const hits=wanted.filter(x=>h.includes(x)).length;if(hits>score){score=hits;best=i}});if(best<0||score<2)throw Error('Header CSV tidak ditemukan. Pastikan ada Kode Item/Nama Item.');return best}
function col(h,names){for(const n of names){const i=h.indexOf(norm(n));if(i>=0)return i}return -1}
function num(v){let s=String(v??'').trim();if(!s)return 0;if(/^[-+]?\d+[.,]\d+$/.test(s))s=s.replace(',','.');else s=s.replace(/\./g,'').replace(',','.');const x=Number(s.replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0}
function mapRows(text){const rows=parseCSV(text);if(rows.length<2)throw Error('CSV kosong.');const hi=findHeader(rows),h=rows[hi].map(norm);const ix={code:col(h,['Kode Item','Kode','Code','SKU','Kode Barang']),barcode:col(h,['Kode Barcode','Barcode','EAN','UPC']),name:col(h,['Nama Item','Nama Barang','Nama','Name','Product Name']),jenis:col(h,['Jenis','Type','Kategori']),brand:col(h,['Merek','Brand']),stok:col(h,['Stok','Stock','Qty','Quantity']),satuan:col(h,['Satuan','Unit']),cost:col(h,['Harga Beli','Harga Pokok','Cost','Purchase Price']),price:col(h,['Harga Jual','Harga','Price','Selling Price']),rak:col(h,['Rak','Lokasi']),supplier:col(h,['Supplier']),note:col(h,['Keterangan','Catatan','Note'])};if(ix.code<0&&ix.barcode<0&&ix.name<0)throw Error('Kolom Nama/Kode/Barcode tidak ditemukan.');const data=[];for(let i=hi+1;i<rows.length;i++){const r=rows[i];const x={code:ix.code>=0?String(r[ix.code]||'').trim():'',barcode:ix.barcode>=0?String(r[ix.barcode]||'').trim():'',name:ix.name>=0?String(r[ix.name]||'').trim():'',jenis:ix.jenis>=0?String(r[ix.jenis]||'').trim():'',brand:ix.brand>=0?String(r[ix.brand]||'').trim():'',satuan:ix.satuan>=0?String(r[ix.satuan]||'').trim():'',stok:ix.stok>=0?num(r[ix.stok]):0,cost:ix.cost>=0?num(r[ix.cost]):0,price:ix.price>=0?num(r[ix.price]):0,rak:ix.rak>=0?String(r[ix.rak]||'').trim():''};if(x.name||x.code||x.barcode)data.push(x)}return data}
function current(){try{return native()?JSON.parse(Android.listProducts('',100000)):[]}catch(e){return[]}}
function status(t,ok=true){const e=$('nfCrudStatus');if(e){e.textContent=t;e.style.color=ok?'#087f63':'#c85050'}}
function backup(){const a=current();if(!a.length){alert('Database item kosong.');return}const head=['Kode Item','Kode Barcode','Nama Item','Jenis','Merek','Stok','Satuan','Harga Beli','Harga Jual','Rak'];const csv='\uFEFF'+head.join(';')+'\n'+a.map(x=>[x.code,x.barcode,x.name,x.jenis,x.brand,x.stok,x.satuan,x.cost??x.purchasePrice??0,x.price,x.rak].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');Android.saveReport('Backup_Item_Naufal_Farma.csv',csv,'text/csv');status('✓ Backup CSV dibuat: '+a.length.toLocaleString('id-ID')+' item.')}
function choose(mode){const input=document.createElement('input');input.type='file';input.accept='.csv,text/csv,*/*';input.onchange=()=>{const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=mapRows(r.result);const res=JSON.parse(Android.importProducts(JSON.stringify(data),mode));if(!res.ok)throw Error(res.error||'Update gagal');status('✓ Selesai: '+(res.added||0)+' baru, '+(res.updated||0)+' diperbarui, total '+(res.total||0)+' item.');if(typeof window.render==='function')window.render()}catch(e){status('✕ '+e.message,false)}};r.readAsText(f,'UTF-8')};input.click()}
function reset(){if(!native())return alert('Database native belum tersedia.');if(!confirm('Reset semua item? Data transaksi tidak disentuh. Disarankan Backup CSV terlebih dahulu.'))return;const res=JSON.parse(Android.importProducts('[]','replace'));if(!res.ok)throw Error(res.error||'Reset gagal');status('✓ Database item berhasil direset.');if(typeof window.render==='function')window.render()}
function install(){const card=document.querySelector('.nf-crud-import');if(!card||card.dataset.nfDbManager)return;card.dataset.nfDbManager='1';const row=document.createElement('div');row.className='nf-db-tools';row.innerHTML='<button id="nfDbUpdate">🔄 Update dari CSV</button><button id="nfDbBackup">📤 Backup CSV</button><button id="nfDbRestore">♻️ Restore CSV</button><button id="nfDbReset">🗑️ Reset Item</button>';card.appendChild(row);const style=document.createElement('style');style.textContent='.nf-db-tools{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.nf-db-tools button{height:40px;border:1px solid #d7e6e1;border-radius:11px;background:#fff;color:#17312b;font-size:11px;font-weight:800}.nf-db-tools #nfDbUpdate{background:#087f63;color:#fff}.nf-db-tools #nfDbReset{color:#b33f3f;background:#fff5f5}';document.head.appendChild(style);$('nfDbUpdate').onclick=()=>choose('add_update');$('nfDbBackup').onclick=backup;$('nfDbRestore').onclick=()=>choose('replace');$('nfDbReset').onclick=()=>{try{reset()}catch(e){status('✕ '+e.message,false)}}}
function boot(){install();setTimeout(install,500);setTimeout(install,1200)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
