(()=>{'use strict';
const CLOUD_URL='https://raw.githubusercontent.com/WRyouAldi/apotek-naufal-farma/main/cloud/xReport2.csv';
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parseCSV(t){t=String(t||'').replace(/^\uFEFF/,'');let delim=';';const sample=t.split(/\r?\n/).slice(0,30).join('\n');const sc=(sample.match(/;/g)||[]).length,co=(sample.match(/,/g)||[]).length,ta=(sample.match(/\t/g)||[]).length;if(co>sc&&co>=ta)delim=',';else if(ta>sc)delim='\t';const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===delim&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);return rows}
const norm=s=>String(s??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const num=v=>{let s=String(v??'').trim();if(!s)return 0;if(/^[-+]?\d+[.,]\d+$/.test(s))s=s.replace(',','.');else s=s.replace(/\./g,'').replace(',','.');const x=Number(s.replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0};
function map(t){const rows=parseCSV(t);if(rows.length<2)throw Error('CSV cloud kosong.');let hi=0,best=0;rows.slice(0,40).forEach((r,i)=>{const h=r.map(norm);const score=['kodeitem','kode','code','kodebarang','barcode','kodebarcode','nama','namaitem','namabarang','name'].filter(x=>h.includes(x)).length;if(score>best){best=score;hi=i}});if(best<2)throw Error('Header CSV cloud tidak dikenali.');const h=rows[hi].map(norm),col=(...a)=>a.map(norm).map(n=>h.indexOf(n)).find(i=>i>=0)??-1;const ix={code:col('Kode Item','Kode','Code','SKU','Kode Barang'),barcode:col('Kode Barcode','Barcode','EAN','UPC'),name:col('Nama Item','Nama Barang','Nama','Name','Product Name'),jenis:col('Jenis','Type','Kategori'),brand:col('Merek','Brand'),stok:col('Stok','Stock','Qty','Quantity'),satuan:col('Satuan','Unit'),cost:col('Harga Beli','Harga Pokok','Cost','Purchase Price'),price:col('Harga Jual','Harga','Price','Selling Price'),rak:col('Rak','Lokasi')};if(ix.code<0&&ix.barcode<0&&ix.name<0)throw Error('Kolom Nama/Kode/Barcode tidak ditemukan.');return rows.slice(hi+1).map(r=>({code:ix.code>=0?String(r[ix.code]||'').trim():'',barcode:ix.barcode>=0?String(r[ix.barcode]||'').trim():'',name:ix.name>=0?String(r[ix.name]||'').trim():'',jenis:ix.jenis>=0?String(r[ix.jenis]||'').trim():'',brand:ix.brand>=0?String(r[ix.brand]||'').trim():'',stok:ix.stok>=0?num(r[ix.stok]):0,cost:ix.cost>=0?num(r[ix.cost]):0,price:ix.price>=0?num(r[ix.price]):0,satuan:ix.satuan>=0?String(r[ix.satuan]||'').trim():'',rak:ix.rak>=0?String(r[ix.rak]||'').trim():''})).filter(x=>x.name||x.code||x.barcode)}
function status(msg,ok=true){const e=$('nfCloudStatus');if(e){e.innerHTML=msg;e.className='nf-cloud-status '+(ok?'ok':'err')}}
async function sync(){const b=$('nfCloudSync');if(b)b.disabled=true;status('☁️ Mengambil CSV terbaru dari GitHub...');try{const res=await fetch(CLOUD_URL+'?t='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error('GitHub mengembalikan HTTP '+res.status);const text=await res.text();const data=map(text);if(!window.Android||typeof Android.importProducts!=='function')throw Error('Database lokal belum siap.');const out=JSON.parse(Android.importProducts(JSON.stringify(data),'add_update'));if(!out.ok)throw Error(out.error||'Update database gagal');localStorage.setItem('naufal_cloud_sync_at',new Date().toISOString());status('✓ Sync berhasil — '+data.length.toLocaleString('id-ID')+' baris CSV. '+(out.added||0)+' baru, '+(out.updated||0)+' diperbarui, total '+(out.total||0)+' item.');if(typeof window.render==='function')window.render()}catch(e){status('✕ Sync gagal: '+esc(e.message),false)}finally{if(b)b.disabled=false}}
function install(){const card=document.querySelector('.nf-crud-import');if(!card||card.dataset.nfCloudSync)return;card.dataset.nfCloudSync='1';const box=document.createElement('div');box.className='nf-cloud-box';box.innerHTML='<div class="nf-cloud-title"><span>☁️</span><div><b>Database Cloud</b><small>GitHub · xReport2.csv</small></div></div><button id="nfCloudSync">🔄 Sync Database</button><div id="nfCloudStatus" class="nf-cloud-status">Belum pernah sync</div>';card.prepend(box);const st=document.createElement('style');st.textContent='.nf-cloud-box{margin-bottom:10px;padding:11px;border:1px solid #d9e8e3;border-radius:13px;background:#f7fbfa}.nf-cloud-title{display:flex;align-items:center;gap:9px;margin-bottom:8px}.nf-cloud-title>span{font-size:21px}.nf-cloud-title b{display:block;font-size:12px;color:#17312b}.nf-cloud-title small{display:block;color:#71807c;font-size:9px;margin-top:2px}.nf-cloud-box button{width:100%;height:40px;border:0;border-radius:10px;background:#087f63;color:#fff;font-weight:800;font-size:11px}.nf-cloud-box button:disabled{opacity:.55}.nf-cloud-status{margin-top:7px;font-size:9px;color:#71807c;line-height:1.35}.nf-cloud-status.ok{color:#087f63}.nf-cloud-status.err{color:#c85050}';document.head.appendChild(st);const last=localStorage.getItem('naufal_cloud_sync_at');if(last)status('Terakhir sync: '+new Date(last).toLocaleString('id-ID'));$('nfCloudSync').onclick=sync}
function boot(){install();setTimeout(install,600);setTimeout(install,1400)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();