(()=>{'use strict';
const CLOUD_CSV='https://raw.githubusercontent.com/WRyouAldi/apotek-naufal-farma/main/cloud/xReport2.csv';
const $=id=>document.getElementById(id);
function cloudStatus(t,ok=true){const e=$('nfCloudStatus');if(e){e.textContent=t;e.style.color=ok?'#087f63':'#b23b3b'}}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;const src=String(text||'').replace(/^\ufeff/,'');const first=src.split(/\r?\n/,1)[0]||'';const semi=(first.split(';').length>first.split(',').length);const d=semi?';':',';for(let i=0;i<src.length;i++){const c=src[i],n=src[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===d&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell.length||row.length){row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row)}return {rows,delimiter:d}}
function norm(s){return String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function findHeader(rows){const aliases={code:['code','kode','kodebarang','kodeitem'],barcode:['barcode','barcodes'],name:['name','nama','namabarang','namaitem'],jenis:['jenis','type','kategori'],brand:['brand','merek'],satuan:['satuan','unit'],price:['price','harga','hargajual','hargajual1'],cost:['cost','hargabeli','hargapokok','purchaseprice','purchase_price'],stok:['stok','stock','qty'],rak:['rak','lokasi']};let best=-1,score=0;for(let i=0;i<Math.min(rows.length,100);i++){const h=rows[i].map(norm);let s=0;Object.values(aliases).forEach(a=>{if(a.some(x=>h.includes(norm(x))))s++});if(s>score){score=s;best=i}}return best>=0&&score>=2?best:-1}
function rowsToItems(rows){const hi=findHeader(rows);if(hi<0)throw Error('Header CSV cloud tidak ditemukan. Pastikan xReport2.csv memiliki Kode/Barcode/Nama.');const h=rows[hi].map(norm);const ix=(...names)=>{for(const n of names){const i=h.indexOf(norm(n));if(i>=0)return i}return -1};const I={code:ix('code','kode','kodebarang','kodeitem'),barcode:ix('barcode'),name:ix('name','nama','namabarang','namaitem'),jenis:ix('jenis','type','kategori'),brand:ix('brand','merek'),satuan:ix('satuan','unit'),price:ix('price','harga','hargajual','hargajual1'),cost:ix('cost','hargabeli','hargapokok','purchaseprice'),stok:ix('stok','stock','qty'),rak:ix('rak','lokasi')};if(I.code<0&&I.barcode<0&&I.name<0)throw Error('Kolom Kode/Barcode/Nama tidak ditemukan.');const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;return rows.slice(hi+1).map(r=>({code:I.code>=0?String(r[I.code]??'').trim():'',barcode:I.barcode>=0?String(r[I.barcode]??'').trim():'',name:I.name>=0?String(r[I.name]??'').trim():'',jenis:I.jenis>=0?String(r[I.jenis]??'').trim():'',brand:I.brand>=0?String(r[I.brand]??'').trim():'',satuan:I.satuan>=0?String(r[I.satuan]??'').trim():'',price:I.price>=0?num(r[I.price]):0,cost:I.cost>=0?num(r[I.cost]):0,stok:I.stok>=0?num(r[I.stok]):0,rak:I.rak>=0?String(r[I.rak]??'').trim():''})).filter(x=>x.code||x.barcode||x.name)}
async function sync(){if(!(window.Android&&typeof Android.importProducts==='function')){cloudStatus('Database native belum tersedia.',false);return}cloudStatus('Mengambil CSV dari GitHub...');try{const r=await fetch(CLOUD_CSV,{cache:'no-store'});if(!r.ok)throw Error('GitHub mengembalikan HTTP '+r.status);const text=await r.text();const parsed=parseCSV(text);const data=rowsToItems(parsed.rows);if(!data.length)throw Error('CSV cloud kosong.');const res=JSON.parse(Android.importProducts(JSON.stringify(data),'add_update'));if(!res.ok)throw Error(res.error||'Sync gagal');const stamp=new Date().toLocaleString('id-ID');cloudStatus('✓ Sync berhasil • '+res.added+' baru • '+res.updated+' diperbarui • '+res.total+' total • '+stamp);localStorage.setItem('nf_cloud_last_sync',stamp)}catch(e){cloudStatus('✕ '+(e.message||'Sync gagal'),false)}}
function init(){if($('nfCloudCard'))return;const host=$('nfItemsHost')||$('daftarItemSection')||document.body;const card=document.createElement('div');card.id='nfCloudCard';card.style.cssText='margin:10px 0;padding:12px;border:1px solid #cfe6df;border-radius:16px;background:linear-gradient(135deg,#eefaf6,#fbfdfc)';card.innerHTML='<div style="font-weight:900;font-size:12px;color:#17312b">☁️ GitHub Cloud Database</div><div style="font-size:9px;color:#72817c;margin:3px 0 9px;line-height:1.4">Sumber data: cloud/xReport2.csv • CSV iPos tetap menjadi format utama.</div><div style="display:flex;gap:7px"><button id="nfCloudSync" style="flex:1;height:42px;background:#087f63;color:#fff;border:0;border-radius:11px;font-weight:800">🔄 Sync dari GitHub</button></div><div id="nfCloudStatus" style="font-size:10px;margin-top:7px;color:#72817c">Belum disinkronkan.</div>';if(host.firstChild)host.insertBefore(card,host.firstChild);else host.appendChild(card);$('nfCloudSync').onclick=sync;const last=localStorage.getItem('nf_cloud_last_sync');if(last)cloudStatus('Sync terakhir: '+last)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,900));else setTimeout(init,900);
window.NFCloudSync=sync;
})();
